### ISSUE TITLE
filtro 'Calidad'

### ISSUE THREAD

**Issue by ander2000** [boldorider4/digital_band_eq#1]
Hi how's everything?
I have a question:
How do the 'Quality' filter values ​​work?

**Comment by boldorider4** [comment]
Hi ander2000,

first of all I am flattered that someone is asking me about something of little to no significance I checked in 5 years ago.

To answer your question: the quality values determine how sharp the filter will cut unwanted frequencies off. Take a band-pass filter as an example: it is shaped like a little bread loaf seen from a side-view (I'm merely describing the shape of its frequency response i.e. the magnitude of its Bode diagram), whereby to the left and to the right of the loaf frequencies are rejected, whereas inside of the loaf frequencies are passing. All good so far?

If the cut of frequencies are, say, 200 Hz and 2 kHz, a high quality filter will be able to reject the closest frequencies to 200 Hz, e.g. 199 Hz, 198 Hz, etc. and also the closest frequencies to 2 kHz, e.g. 2050 Hz, 2100 Hz, etc. Conversely, low quality values will be less effective at rejecting those frequencies, shaping the loaf more like a trapezoid, meaning the filter will be increasingly able to reject unwanted frequencies as the signal is moving farther from those cut-off values e.g. 100 Hz, 90 Hz, 80 Hz for the low cut-off value and 3 kHz, 4 kHz, 5 kHz for the high cut-off. So far so good?

Now you may ask: why would anyone want to choose low quality values? Well, the reason is that the quality of the filter always need to be traded off with how much ripple (this is too hard to explain but you can look it up) you're going to get i.e. how much distortion you will have on the *passed* signal (inside the loaf) as you move close to the cut-off frequencies e.g. 210 Hz, 220 Hz, 230 Hz, etc. and 1800 Hz, 1900 Hz, 1950 Hz, etc.

Hope I could make my point. Feel free to ask any more questions!

Take care.

**Comment by ander2000** [comment]
Thank you very much for answering and for your good explanation.
So what values ​​should I put in the "array_Q"?

**Comment by boldorider4** [comment]
Hi ander2000,

so, on the README on the master branch I inserted a reference link, you may want to check it out:
http://www.learningaboutelectronics.com/Articles/Quality-factor-calculator.php

this gives you an even better explanation of how a quality factor is calculated.
By the way, there was a mistake in my implementation/documentation. In a band pass filter Q is defined as:

Q = f_0/ (f2 - f1)

where f_0 is the center frequency and f2 and f1 are the 3dB cutoff frequencies.

For Q array you will want to insert values depending on the f_0, f_1 and f_2 you want for your filters. Each (f_0, f_1, f_2) tuple represents one filter in your filter bank. So the size of Q depends on how many filters you want to have in your filter bank.
Ideally, Q should not be larger than 10 or smaller than .1 for stability (i.e. to avoid ugly ripple).

I hope this explains better! Sorry for mistakes and bugs I may have left in the implementation, the thing is this repo hasn't been properly taken care of in years!

-Jack

**Comment by ander2000** [comment]
Calm. Thank you very much for your explanations and for this project. :) :)
